# Generated by Django 3.0.6 on 2020-05-09 08:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageprocessing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userandencodingdetails',
            name='encoding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
    ]
