# Generated by Django 3.0.6 on 2020-05-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageprocessing', '0002_auto_20200509_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userandencodingdetails',
            name='PersonName',
        ),
        migrations.AddField(
            model_name='userandencodingdetails',
            name='person_name',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
