# Generated by Django 3.0.6 on 2020-05-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageprocessing', '0006_auto_20200509_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userandencodingdetail',
            name='encoding',
            field=models.TextField(),
        ),
    ]
