# Generated by Django 3.0.6 on 2020-05-09 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageprocessing', '0003_auto_20200509_0831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAndEncodingDetails',
            new_name='UserAndEncodingDetail',
        ),
    ]
