# Generated by Django 3.0.6 on 2020-05-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageprocessing', '0005_auto_20200509_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userandencodingdetail',
            name='encoding',
            field=models.BinaryField(),
        ),
    ]
